services:
  postgres:
    image: cmdrmark/server:postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    mem_limit: 512m
    cpus: 1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  py-server:
    image: cmdrmark/server:py
    container_name: py_server
    restart: always
    mem_limit: 1G
    cpus: 1
    ports:
      - "9090:9090"
    environment:
      DOCKER: "TRUE"
      DB_NAME: "mydatabase"
      DB_USER: "myuser"
      DB_PASSWORD: "mypassword"
      DB_HOST: "postgres"
      DB_PORT: "5432"
    depends_on:
      - postgres

  go-server:
    image: cmdrmark/server:go
    container_name: go_server
    restart: always
    mem_limit: 512m
    cpus: 2
    ports:
      - "8080:8080"
    environment:
      DOCKER: "TRUE"
      DB_NAME: "mydatabase"
      DB_USER: "myuser"
      DB_PASSWORD: "mypassword"
      DB_HOST: "postgres"
      DB_PORT: "5432"
    depends_on:
      - postgres

volumes:
  postgres_data: